export const goalOptions = [
  {
    id: 'buy_home',
    title: 'Buy a Home',
    description: 'Avoid risky moves before lender review.',
    timelinePrompt: 'When do you want to apply for a mortgage?',
  },
  {
    id: 'buy_car',
    title: 'Buy a Car',
    description: 'Prepare for auto financing and better rates.',
    timelinePrompt: 'When do you want to shop for an auto loan?',
  },
  {
    id: 'rebuild_credit',
    title: 'Rebuild Credit',
    description: 'Focus on safer steps that support recovery.',
    timelinePrompt: 'How soon do you want to see progress?',
  },
  {
    id: 'fix_collections',
    title: 'Fix Collections',
    description: 'Understand what to review before acting.',
    timelinePrompt: 'How urgent is the collection issue?',
  },
  {
    id: 'build_from_scratch',
    title: 'Build Credit From Scratch',
    description: 'Start with low-risk building blocks.',
    timelinePrompt: 'How long do you want your starter plan to be?',
  },
  {
    id: 'lower_rates',
    title: 'Get Better Rates',
    description: 'Lower risk before refinancing or applying.',
    timelinePrompt: 'When are you trying to qualify?',
  },
  {
    id: 'business_funding',
    title: 'Business Funding',
    description: 'Protect personal profile before funding review.',
    timelinePrompt: 'When do you need funding readiness?',
  },
  {
    id: 'apartment_approval',
    title: 'Apartment Approval',
    description: 'Reduce avoidable red flags before screening.',
    timelinePrompt: 'When are you applying for an apartment?',
  },
];

export const quizSteps = [
  {
    id: 'score_range',
    label: 'About where is your credit score today?',
    helper: 'A range is enough. Limitless Credit GPS does not need an exact score for the MVP.',
    type: 'choice',
    options: ['Under 500', '500-579', '580-639', '640-699', '700-759', '760+', 'Not sure'],
  },
  {
    id: 'goal_timeline',
    label: 'What is your timeline?',
    helper: 'Short timelines make new credit and account changes more sensitive.',
    type: 'choice',
    options: ['30 days', '60-90 days', '3-6 months', '6-12 months', 'More than 12 months', 'Not sure'],
  },
  {
    id: 'number_cards',
    label: 'How many credit cards do you have?',
    helper: 'This helps estimate whether your profile is thin, established, or balance-heavy.',
    type: 'choice',
    options: ['0', '1', '2-3', '4-6', '7+'],
  },
  {
    id: 'total_card_balance',
    label: 'About how much total credit card balance is reporting?',
    helper: 'Use your best estimate across all cards.',
    type: 'money',
    placeholder: '2400',
  },
  {
    id: 'total_card_limit',
    label: 'About what is your total credit limit?',
    helper: 'Total limits help estimate utilization.',
    type: 'money',
    placeholder: '8000',
  },
  {
    id: 'has_late_payments',
    label: 'Any late payments on your reports?',
    helper: 'Payment history is one of the largest score categories.',
    type: 'boolean',
  },
  {
    id: 'has_collections',
    label: 'Any collections reporting?',
    helper: 'Collections often need extra care before taking action.',
    type: 'boolean',
  },
  {
    id: 'has_chargeoffs',
    label: 'Any charge-offs reporting?',
    helper: 'Charge-offs can affect lender review and rebuilding strategy.',
    type: 'boolean',
  },
  {
    id: 'loan_mix',
    label: 'Which loans do you currently have?',
    helper: 'Account mix matters less than paying on time, but it can explain movement.',
    type: 'multi',
    options: [
      { id: 'has_auto_loan', label: 'Auto loan' },
      { id: 'has_mortgage', label: 'Mortgage' },
      { id: 'has_student_loans', label: 'Student loans' },
    ],
  },
  {
    id: 'planned_major_purchase',
    label: 'Any major purchase planned?',
    helper: 'A planned home, car, or apartment application changes the safer route.',
    type: 'choice',
    options: ['Mortgage', 'Auto loan', 'Apartment', 'Business funding', 'No major purchase', 'Not sure'],
  },
  {
    id: 'applying_soon',
    label: 'Are you applying for credit, housing, or funding soon?',
    helper: 'If yes, the app will show stronger caution around inquiries and new accounts.',
    type: 'boolean',
  },
];

export const defaultProfile = {
  id: 'local-demo-profile',
  user_id: 'local-demo-user',
  score_range: '640-699',
  primary_goal: 'buy_home',
  goal_timeline: '3-6 months',
  number_cards: '2-3',
  total_card_balance: 4200,
  total_card_limit: 11000,
  has_late_payments: false,
  has_collections: true,
  has_chargeoffs: false,
  has_auto_loan: true,
  has_mortgage: false,
  has_student_loans: false,
  planned_major_purchase: 'Mortgage',
  applying_soon: false,
  onboarding_completed: false,
};

export const scenarioOptions = [
  {
    id: 'pay_down_credit_card',
    title: 'Pay off credit card',
    description: 'Estimate utilization impact and reporting timing.',
  },
  {
    id: 'pay_off_auto_loan',
    title: 'Pay off car loan',
    description: 'Check account-mix and installment-loan tradeoffs.',
  },
  {
    id: 'pay_off_mortgage',
    title: 'Pay off mortgage',
    description: 'Understand why a responsible payoff can still move scores.',
  },
  {
    id: 'open_new_card',
    title: 'Open new card',
    description: 'Compare inquiry, new account age, and utilization effects.',
  },
  {
    id: 'close_card',
    title: 'Close old card',
    description: 'See whether available credit and age could become a risk.',
  },
  {
    id: 'request_limit_increase',
    title: 'Request limit increase',
    description: 'Estimate utilization upside and hard-pull caution.',
  },
  {
    id: 'pay_collection',
    title: 'Pay collection',
    description: 'Review model, status, and accuracy caveats before acting.',
  },
  {
    id: 'remove_inaccurate_item',
    title: 'Remove inaccurate account',
    description: 'Learn what may happen if an inaccurate negative item is corrected.',
  },
  {
    id: 'consolidate_debt',
    title: 'Consolidate debt',
    description: 'Balance payoff benefits against new-loan friction.',
  },
  {
    id: 'apply_for_mortgage',
    title: 'Apply for mortgage',
    description: 'Spot credit moves to avoid before lender review.',
  },
  {
    id: 'missed_payment',
    title: 'Miss a payment',
    description: 'Understand why this is one of the highest-risk events.',
  },
];

export const actionPlanItems = [
  {
    id: 'lower-utilization',
    title: 'Lower card utilization',
    description: 'Aim to report lower balances before the next statement date.',
    priority: 'High',
    estimated_impact: 'Likely Positive',
    risk_level: 'Low',
    due_window: 'Next 30 days',
  },
  {
    id: 'pause-new-credit',
    title: 'Pause unnecessary applications',
    description: 'Protect the file from avoidable inquiries and new account age changes.',
    priority: 'High',
    estimated_impact: 'Risk reduction',
    risk_level: 'Low',
    due_window: 'Until goal review',
  },
  {
    id: 'review-negative-items',
    title: 'Review questionable negative items',
    description: 'Check collections, charge-offs, dates, balances, and ownership before acting.',
    priority: 'Medium',
    estimated_impact: 'Depends on Profile',
    risk_level: 'Medium',
    due_window: 'Next 14 days',
  },
  {
    id: 'learn-utilization',
    title: 'Finish the utilization lesson',
    description: 'Learn how statement dates and reported balances can affect your plan.',
    priority: 'Medium',
    estimated_impact: 'Better decisions',
    risk_level: 'Low',
    due_window: 'This week',
  },
];

export const lessons = [
  {
    id: 'credit-score-basics',
    title: 'Credit Score Basics',
    category: 'Basics',
    reading_level: 'High school',
    summary: 'Scores react to reported information, not always what you did today.',
    simple: 'A credit score is a quick risk signal built from what appears on your credit reports.',
    example: 'If your card balance reports high today, the score can react even if you plan to pay it tomorrow.',
    mistake: 'Do not assume a score app updates the same day you make a payment.',
    action: 'Check which accounts updated before deciding why a score moved.',
    related_scenarios: ['pay_down_credit_card', 'open_new_card'],
  },
  {
    id: 'payment-history',
    title: 'Payment History',
    category: 'Score Factors',
    reading_level: 'High school',
    summary: 'Paying on time is the foundation of the plan.',
    simple: 'Payment history shows whether accounts were paid as agreed.',
    example: 'A 30-day late payment can matter more than a small balance change.',
    mistake: 'Do not skip a minimum payment while waiting to make a larger payment.',
    action: 'Set automatic minimum payments on every account.',
    related_scenarios: ['missed_payment'],
  },
  {
    id: 'credit-utilization',
    title: 'Credit Utilization: The Fastest Lever Most People Miss',
    category: 'Score Factors',
    reading_level: 'High school',
    summary: 'Utilization compares card balances with card limits.',
    simple: 'Lower reported card balances can make the same profile look less risky.',
    example: 'A $900 balance on a $1,000 limit looks heavier than $900 on a $5,000 limit.',
    mistake: 'Do not wait until after the statement closes if you need a lower balance to report.',
    action: 'Pay before the statement date when possible.',
    related_scenarios: ['pay_down_credit_card', 'request_limit_increase', 'close_card'],
  },
  {
    id: 'credit-age',
    title: 'Credit Age',
    category: 'Score Factors',
    reading_level: 'High school',
    summary: 'Older accounts can help show experience with credit.',
    simple: 'Credit age looks at how long accounts have been open and the average age of accounts.',
    example: 'Opening several new accounts can make the file look younger.',
    mistake: 'Do not close an old card right before a major application without checking utilization.',
    action: 'Keep older no-fee cards active with small planned use.',
    related_scenarios: ['open_new_card', 'close_card'],
  },
  {
    id: 'credit-mix',
    title: 'Credit Mix',
    category: 'Score Factors',
    reading_level: 'High school',
    summary: 'Different account types can explain small score changes.',
    simple: 'A profile may include revolving accounts like cards and installment accounts like auto loans.',
    example: 'Paying off your only installment loan can sometimes create a temporary score dip.',
    mistake: 'Do not keep expensive debt just to protect a score.',
    action: 'Make financial decisions first, then plan around reporting effects.',
    related_scenarios: ['pay_off_auto_loan', 'pay_off_mortgage'],
  },
  {
    id: 'new-credit-inquiries',
    title: 'New Credit / Inquiries',
    category: 'Applications',
    reading_level: 'High school',
    summary: 'New applications can create short-term friction.',
    simple: 'A hard inquiry means a lender checked your credit because you applied.',
    example: 'A new card before mortgage underwriting may create avoidable questions.',
    mistake: 'Do not stack applications when a major loan is close.',
    action: 'Pause new credit when you are within 90 days of a mortgage or auto loan.',
    related_scenarios: ['open_new_card', 'apply_for_mortgage'],
  },
  {
    id: 'collections',
    title: 'Collections',
    category: 'Negative Items',
    reading_level: 'High school',
    summary: 'Collections need careful review before payment decisions.',
    simple: 'A collection is usually a debt that a creditor or collector says is past due.',
    example: 'Paying may help some lender reviews, but it may not immediately raise every score.',
    mistake: 'Do not assume payment guarantees deletion or a score increase.',
    action: 'Confirm accuracy, ownership, amount, age, and written terms.',
    related_scenarios: ['pay_collection', 'remove_inaccurate_item'],
  },
  {
    id: 'charge-offs',
    title: 'Charge-Offs',
    category: 'Negative Items',
    reading_level: 'High school',
    summary: 'A charge-off can still matter after the original account closes.',
    simple: 'A charge-off means a creditor wrote the account off as a loss, but reporting and collection activity may continue.',
    example: 'A paid charge-off can still appear as a negative account if the reporting is accurate.',
    mistake: 'Do not ignore account details, dates, balances, or ownership.',
    action: 'Review the report entry before deciding what to do next.',
    related_scenarios: ['remove_inaccurate_item', 'pay_collection'],
  },
  {
    id: 'mortgage-prep',
    title: 'Mortgage Prep',
    category: 'Goal Prep',
    reading_level: 'High school',
    summary: 'Mortgage timelines reward stability.',
    simple: 'Before a mortgage, avoid moves that create new risk signals unless a professional says they fit.',
    example: 'Opening a new card within 90 days can add a hard inquiry and a new account.',
    mistake: 'Do not chase points with risky new credit before underwriting.',
    action: 'Keep balances low, payments on time, and documents ready.',
    related_scenarios: ['apply_for_mortgage', 'open_new_card'],
  },
  {
    id: 'auto-loan-prep',
    title: 'Auto Loan Prep',
    category: 'Goal Prep',
    reading_level: 'High school',
    summary: 'Auto loan prep is about lowering avoidable risk before shopping.',
    simple: 'Lenders may consider score range, recent inquiries, income, debt, and history.',
    example: 'Lowering card balances before shopping may improve your profile fit.',
    mistake: 'Do not open unnecessary new accounts right before rate shopping.',
    action: 'Simulate balance payoff and new-card moves first.',
    related_scenarios: ['pay_down_credit_card', 'open_new_card'],
  },
  {
    id: 'apartment-approval-prep',
    title: 'Apartment Approval Prep',
    category: 'Goal Prep',
    reading_level: 'High school',
    summary: 'Housing screenings may care about collections and recent payment issues.',
    simple: 'An apartment review can look beyond the score number.',
    example: 'A fresh collection can create concern even if your score is not terrible.',
    mistake: 'Do not apply without checking whether negative items are accurate.',
    action: 'Review reports and prepare explanations or documentation.',
    related_scenarios: ['pay_collection', 'remove_inaccurate_item'],
  },
  {
    id: 'credit-rebuilding',
    title: 'Credit Rebuilding',
    category: 'Rebuild',
    reading_level: 'High school',
    summary: 'Rebuilding works best with small repeatable moves.',
    simple: 'The basics are on-time payments, low reported balances, and careful new credit.',
    example: 'A secured card used lightly can help if paid on time and kept low.',
    mistake: 'Do not apply for many products at once.',
    action: 'Pick one builder tool, keep balances low, and track reporting.',
    related_scenarios: ['open_new_card', 'request_limit_increase'],
  },
  {
    id: 'credit-myths',
    title: 'Credit Myths',
    category: 'Basics',
    reading_level: 'High school',
    summary: 'Some popular credit advice is incomplete.',
    simple: 'Credit decisions depend on your goal, timing, and profile.',
    example: 'Paying off debt is good, but the score reaction depends on what reports.',
    mistake: 'Do not follow one-size-fits-all advice before a major loan.',
    action: 'Run the simulator before making a credit move.',
    related_scenarios: ['pay_off_auto_loan', 'close_card'],
  },
  {
    id: 'debt-collector-basics',
    title: 'Debt Collector Basics',
    category: 'Negative Items',
    reading_level: 'High school',
    summary: 'Know what to document before talking to collectors.',
    simple: 'Collectors may contact you about debts, but details matter.',
    example: 'The account owner, amount, dates, and written terms can affect your options.',
    mistake: 'Do not rely on a phone promise without written confirmation.',
    action: 'Save letters, dates, names, and account details.',
    related_scenarios: ['pay_collection'],
  },
  {
    id: 'identity-theft-basics',
    title: 'Identity Theft Basics',
    category: 'Protection',
    reading_level: 'High school',
    summary: 'Act quickly when an account is not yours.',
    simple: 'Identity theft means someone may have used your information without permission.',
    example: 'A card you never opened or an address you never used should be reviewed.',
    mistake: 'Do not ignore unfamiliar accounts or inquiries.',
    action: 'Document what is wrong and request a deeper review if legal or dispute questions come up.',
    related_scenarios: ['remove_inaccurate_item'],
  },
];

export const offers = [
  {
    id: 'secured-builder-card',
    title: 'Secured Builder Card',
    category: 'Secured cards',
    best_for: 'Building credit from scratch or rebuilding',
    why_it_may_fit: 'May help establish revolving history when used lightly and paid on time.',
    risk_note: 'A deposit may be required. Approval is not guaranteed.',
    affiliate_url: '#review-secured-builder-card',
  },
  {
    id: 'credit-builder-loan',
    title: 'Credit Builder Loan',
    category: 'Credit builder loans',
    best_for: 'Adding installment history carefully',
    why_it_may_fit: 'May support payment history if monthly payments are affordable.',
    risk_note: 'Missed payments can hurt. Review fees and terms before applying.',
    affiliate_url: '#review-credit-builder-loan',
  },
  {
    id: 'identity-protection',
    title: 'Identity Protection Monitor',
    category: 'Identity protection',
    best_for: 'Users with unfamiliar accounts or inquiry concerns',
    why_it_may_fit: 'May help monitor changes while you review questionable reporting.',
    risk_note: 'Monitoring does not remove inaccurate items by itself.',
    affiliate_url: '#review-identity-protection',
  },
  {
    id: 'debt-payoff-tool',
    title: 'Debt Payoff Planner',
    category: 'Debt payoff tools',
    best_for: 'Lowering utilization without adding new credit',
    why_it_may_fit: 'May help choose which balances to pay before statement dates.',
    risk_note: 'Budget results depend on income, spending, and payoff discipline.',
    affiliate_url: '#review-debt-payoff-tool',
  },
  {
    id: 'mortgage-readiness',
    title: 'Mortgage Readiness Partner',
    category: 'Mortgage readiness partners',
    best_for: 'Home buyers within 3-6 months',
    why_it_may_fit: 'May help review credit timing before lender conversations.',
    risk_note: 'This is educational guidance. Loan approval is not guaranteed.',
    affiliate_url: '#review-mortgage-readiness',
  },
];
