const DEFAULT_MODEL = process.env.APPBUILDER_MODEL || 'gpt-4.1-mini';
const MAX_HISTORY_ITEMS = 8;
const MAX_FILE_CONTEXT = 8;
const MAX_FILE_CONTENT_CHARS = 1800;

function parseRequestBody(body) {
  if (!body) {
    return {};
  }

  if (typeof body === 'string') {
    try {
      return JSON.parse(body);
    } catch {
      return {};
    }
  }

  if (typeof body === 'object') {
    return body;
  }

  return {};
}

function toSafeString(value, fallback = '') {
  const output = String(value || '').trim();
  return output || fallback;
}

function toTitleCase(value) {
  return String(value || '')
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1).toLowerCase())
    .join(' ')
    .trim();
}

function sanitizeHexColor(value) {
  const candidate = String(value || '').trim();
  return /^#[0-9a-fA-F]{6}$/.test(candidate) ? candidate : '#0891B2';
}

function sanitizeFilePath(filePath) {
  return String(filePath || '')
    .replace(/^\/+/, '')
    .replace(/\.\./g, '')
    .trim();
}

function sanitizeFiles(files) {
  if (!files || typeof files !== 'object') {
    return {};
  }

  const output = {};
  for (const [filePath, value] of Object.entries(files)) {
    if (typeof value !== 'string') {
      continue;
    }

    const safePath = sanitizeFilePath(filePath);
    if (!safePath) {
      continue;
    }

    output[safePath] = value;
  }

  return output;
}

function normalizeConfig(config) {
  const input = config && typeof config === 'object' ? config : {};
  const allowedTemplates = new Set(['custom', 'commerce', 'operations', 'community', 'content']);
  const allowedAudiences = new Set(['consumers', 'members', 'field-team', 'internal-team', 'hybrid']);
  const allowedCapabilities = new Set([
    'auth',
    'dashboard',
    'payments',
    'notifications',
    'chat',
    'analytics',
    'bookings',
    'map',
  ]);

  const capabilities = Array.isArray(input.capabilities)
    ? input.capabilities
        .map((capability) => String(capability || '').trim().toLowerCase())
        .filter((capability) => allowedCapabilities.has(capability))
        .slice(0, 8)
    : [];

  return {
    appName: toSafeString(input.appName),
    template: allowedTemplates.has(String(input.template || '').toLowerCase())
      ? String(input.template || '').toLowerCase()
      : 'custom',
    audience: allowedAudiences.has(String(input.audience || '').toLowerCase())
      ? String(input.audience || '').toLowerCase()
      : 'consumers',
    businessGoal: toSafeString(input.businessGoal, 'Ship quickly and validate demand'),
    primaryColor: sanitizeHexColor(input.primaryColor),
    capabilities,
  };
}

function normalizePayload(payload) {
  const files = sanitizeFiles(payload?.files);
  const screens = Array.isArray(payload?.preview?.screens)
    ? payload.preview.screens.slice(0, 5).map((screen, index) => ({
        name: toSafeString(screen?.name, `Screen ${index + 1}`),
        purpose: toSafeString(screen?.purpose, 'Primary workflow screen'),
        elements: Array.isArray(screen?.elements)
          ? screen.elements.slice(0, 5).map((element) => toSafeString(element)).filter(Boolean)
          : [],
      }))
    : [];

  return {
    assistantMessage: toSafeString(payload?.assistantMessage, 'Generated project update.'),
    project: {
      name: toSafeString(payload?.project?.name, 'EB28 Mobile App'),
      description: toSafeString(payload?.project?.description, 'Expo React Native project generated from brief.'),
      platform: toSafeString(payload?.project?.platform, 'expo-react-native'),
    },
    preview: {
      appName: toSafeString(payload?.preview?.appName, payload?.project?.name || 'EB28 Mobile App'),
      tagline: toSafeString(payload?.preview?.tagline, 'Product scaffold generated by EB28 App Builder'),
      primaryColor: sanitizeHexColor(payload?.preview?.primaryColor),
      screens: screens.length > 0
        ? screens
        : [
            {
              name: 'Home',
              purpose: 'Primary app experience',
              elements: ['Headline', 'Quick actions', 'Status cards'],
            },
          ],
    },
    files,
    changes: Array.isArray(payload?.changes)
      ? payload.changes.slice(0, 12).map((item) => toSafeString(item)).filter(Boolean)
      : [],
  };
}

function normalizeHistory(history) {
  if (!Array.isArray(history)) {
    return [];
  }

  return history
    .slice(-MAX_HISTORY_ITEMS)
    .map((entry) => ({
      role: entry?.role === 'assistant' ? 'assistant' : 'user',
      content: toSafeString(entry?.content),
    }))
    .filter((entry) => entry.content.length > 0);
}

function compactCurrentFiles(currentFiles) {
  const safeFiles = sanitizeFiles(currentFiles);
  const paths = Object.keys(safeFiles).sort().slice(0, MAX_FILE_CONTEXT);

  return paths
    .map((filePath) => {
      const content = safeFiles[filePath].slice(0, MAX_FILE_CONTENT_CHARS);
      return `FILE: ${filePath}\n${content}`;
    })
    .join('\n\n');
}

function inferAppName(prompt) {
  const words = String(prompt || '')
    .replace(/[^a-zA-Z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 3);

  const candidate = toTitleCase(words.join(' '));
  if (candidate.length >= 3) {
    return `${candidate} App`;
  }

  return 'EB28 Mobile App';
}

function capabilityLabel(id) {
  const map = {
    auth: 'Sign In and onboarding',
    dashboard: 'Operational dashboard cards',
    payments: 'Checkout and payment flow',
    notifications: 'Notification center',
    chat: 'In-app messaging',
    analytics: 'Usage analytics surfaces',
    bookings: 'Scheduling and bookings',
    map: 'Map and location workflows',
  };
  return map[id] || toTitleCase(id);
}

function escapeTemplateString(value) {
  return String(value || '')
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
}

function buildFallbackProject({ prompt, rawPrompt, currentFiles, config }) {
  const appName = config.appName || inferAppName(rawPrompt || prompt);
  const capabilities = config.capabilities.length > 0 ? config.capabilities : ['auth', 'dashboard', 'notifications'];
  const featureLabels = capabilities.map(capabilityLabel).slice(0, 6);

  const description = `EB28 App Builder scaffold for ${config.audience}.`;
  const featureItems = featureLabels
    .map((feature, index) => `            <Text style={styles.itemText}>${index + 1}. ${escapeTemplateString(feature)}</Text>`)
    .join('\n');

  const files = {
    '.gitignore': 'node_modules\\n.expo\\n.DS_Store\\n',
    'package.json': JSON.stringify(
      {
        name: appName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 40) || 'eb28-mobile-app',
        version: '1.0.0',
        private: true,
        main: 'node_modules/expo/AppEntry.js',
        scripts: {
          start: 'expo start',
          android: 'expo start --android',
          ios: 'expo start --ios',
          web: 'expo start --web',
        },
        dependencies: {
          expo: '^53.0.0',
          react: '^19.0.0',
          'react-native': '^0.79.0',
          'expo-status-bar': '~2.2.0',
        },
      },
      null,
      2
    ),
    'app.json': JSON.stringify(
      {
        expo: {
          name: appName,
          slug: appName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 40) || 'eb28-mobile-app',
          version: '1.0.0',
          orientation: 'portrait',
          userInterfaceStyle: 'automatic',
          ios: {
            supportsTablet: true,
          },
          android: {
            adaptiveIcon: {
              backgroundColor: '#ffffff',
            },
          },
          web: {
            bundler: 'metro',
          },
        },
      },
      null,
      2
    ),
    'babel.config.js': [
      'module.exports = function(api) {',
      '  api.cache(true);',
      '  return {',
      "    presets: ['babel-preset-expo'],",
      '  };',
      '};',
      '',
    ].join('\n'),
    'App.js': [
      "import React from 'react';",
      "import { SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, View } from 'react-native';",
      '',
      `const accent = '${config.primaryColor}';`,
      '',
      'export default function App() {',
      '  return (',
      '    <SafeAreaView style={styles.safe}>',
      '      <StatusBar barStyle="light-content" />',
      '      <ScrollView contentContainerStyle={styles.container}>',
      '        <View style={styles.hero}>',
      `          <Text style={styles.title}>${escapeTemplateString(appName)}</Text>`,
      `          <Text style={styles.subtitle}>${escapeTemplateString(config.businessGoal)}</Text>`,
      '        </View>',
      '        <View style={styles.card}>',
      `          <Text style={styles.sectionLabel}>${escapeTemplateString(toTitleCase(config.template))} capability set</Text>`,
      featureItems,
      '        </View>',
      '      </ScrollView>',
      '    </SafeAreaView>',
      '  );',
      '}',
      '',
      'const styles = StyleSheet.create({',
      '  safe: {',
      '    flex: 1,',
      '    backgroundColor: "#030712",',
      '  },',
      '  container: {',
      '    padding: 20,',
      '    gap: 16,',
      '  },',
      '  hero: {',
      '    borderRadius: 16,',
      '    padding: 18,',
      '    backgroundColor: accent,',
      '  },',
      '  title: {',
      '    color: "white",',
      '    fontSize: 28,',
      '    fontWeight: "700",',
      '  },',
      '  subtitle: {',
      '    marginTop: 6,',
      '    color: "#e2e8f0",',
      '    fontSize: 14,',
      '    lineHeight: 20,',
      '  },',
      '  card: {',
      '    borderRadius: 16,',
      '    backgroundColor: "#111827",',
      '    borderWidth: 1,',
      '    borderColor: "#1f2937",',
      '    padding: 16,',
      '    gap: 10,',
      '  },',
      '  sectionLabel: {',
      '    color: "#f8fafc",',
      '    fontWeight: "700",',
      '    fontSize: 16,',
      '  },',
      '  itemText: {',
      '    color: "#cbd5e1",',
      '    fontSize: 14,',
      '    lineHeight: 20,',
      '  },',
      '});',
      '',
    ].join('\n'),
    'README.md': [
      `# ${appName}`,
      '',
      description,
      '',
      '## Run locally',
      '',
      '```bash',
      'npm install',
      'npm run start',
      '```',
      '',
      'Scan the Expo Go QR code to preview on device.',
      '',
      '## Build brief',
      '',
      `Template: ${toTitleCase(config.template)}`,
      `Audience: ${toTitleCase(config.audience.replace('-', ' '))}`,
      `Goal: ${config.businessGoal}`,
      `Color: ${config.primaryColor}`,
      '',
      rawPrompt || prompt,
      '',
    ].join('\n'),
  };

  const hasExistingFiles = currentFiles && Object.keys(sanitizeFiles(currentFiles)).length > 0;

  return {
    assistantMessage: hasExistingFiles
      ? `Generated a new EB28 App Builder iteration for ${appName}.`
      : `Created the first EB28 App Builder scaffold for ${appName}.`,
    project: {
      name: appName,
      description,
      platform: 'expo-react-native',
    },
    preview: {
      appName,
      tagline: featureLabels[0] || 'Product scaffold generated by EB28',
      primaryColor: config.primaryColor,
      screens: [
        {
          name: 'Home',
          purpose: 'Primary value delivery surface',
          elements: featureLabels.slice(0, 3),
        },
        {
          name: 'Operations',
          purpose: 'Execution and management workflow',
          elements: featureLabels.slice(1, 4),
        },
      ],
    },
    files,
    changes: [
      hasExistingFiles
        ? 'Applied your latest brief as a new scaffold version.'
        : 'Generated full Expo scaffold from your build brief.',
      'Configured runtime scripts and app metadata.',
      'Aligned screens and features with selected template and audience.',
      'Prepared handoff README with run instructions.',
    ],
    source: 'fallback-template',
    model: 'template-v2',
  };
}

async function generateWithOpenAI({ prompt, rawPrompt, history, currentFiles, config }) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return null;
  }

  const historyLines = normalizeHistory(history)
    .map((entry) => `${entry.role.toUpperCase()}: ${entry.content}`)
    .join('\n');

  const fileContext = compactCurrentFiles(currentFiles);

  const schema = {
    name: 'eb28_app_builder_output',
    strict: true,
    schema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        assistantMessage: { type: 'string' },
        project: {
          type: 'object',
          additionalProperties: false,
          properties: {
            name: { type: 'string' },
            description: { type: 'string' },
            platform: { type: 'string' },
          },
          required: ['name', 'description', 'platform'],
        },
        preview: {
          type: 'object',
          additionalProperties: false,
          properties: {
            appName: { type: 'string' },
            tagline: { type: 'string' },
            primaryColor: { type: 'string' },
            screens: {
              type: 'array',
              maxItems: 5,
              items: {
                type: 'object',
                additionalProperties: false,
                properties: {
                  name: { type: 'string' },
                  purpose: { type: 'string' },
                  elements: {
                    type: 'array',
                    maxItems: 5,
                    items: { type: 'string' },
                  },
                },
                required: ['name', 'purpose', 'elements'],
              },
            },
          },
          required: ['appName', 'tagline', 'primaryColor', 'screens'],
        },
        files: {
          type: 'object',
          minProperties: 4,
          maxProperties: 20,
          additionalProperties: {
            type: 'string',
          },
        },
        changes: {
          type: 'array',
          maxItems: 12,
          items: { type: 'string' },
        },
      },
      required: ['assistantMessage', 'project', 'preview', 'files', 'changes'],
    },
  };

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: DEFAULT_MODEL,
      temperature: 0.2,
      response_format: {
        type: 'json_schema',
        json_schema: schema,
      },
      messages: [
        {
          role: 'system',
          content: [
            'You are EB28 App Builder, generating Expo React Native project scaffolds.',
            'Return a compact but runnable project structure with coherent files.',
            'Always include package.json, app.json, App.js, README.md, and any additional supporting files.',
            'When current files are provided, produce a full updated file set instead of only a diff.',
            'Respect user configuration for app name, color, audience, template, and capabilities.',
            'Output valid JSON only via the enforced schema.',
          ].join(' '),
        },
        {
          role: 'user',
          content: [
            `Build brief: ${prompt}`,
            '',
            `Raw direction: ${rawPrompt || prompt}`,
            '',
            `Config: ${JSON.stringify(config)}`,
            '',
            'Recent history:',
            historyLines || '(no history)',
            '',
            'Current file context (trimmed):',
            fileContext || '(no existing files)',
          ].join('\n'),
        },
      ],
    }),
  });

  const payload = await response.json();

  if (!response.ok) {
    throw new Error(payload?.error?.message || 'OpenAI request failed');
  }

  const rawContent = payload?.choices?.[0]?.message?.content;
  const parsed = JSON.parse(rawContent || '{}');
  const normalized = normalizePayload(parsed);

  return {
    ...normalized,
    source: 'openai',
    model: payload?.model || DEFAULT_MODEL,
  };
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const body = parseRequestBody(req.body);
  const prompt = toSafeString(body?.prompt);
  const rawPrompt = toSafeString(body?.rawPrompt, prompt);
  const currentFiles = sanitizeFiles(body?.currentFiles);
  const history = normalizeHistory(body?.history);
  const config = normalizeConfig(body?.config);

  if (!prompt) {
    return res.status(400).json({ error: 'Prompt is required.' });
  }

  try {
    const openAIResult = await generateWithOpenAI({
      prompt,
      rawPrompt,
      history,
      currentFiles,
      config,
    });

    if (openAIResult) {
      return res.status(200).json(openAIResult);
    }

    return res.status(200).json(buildFallbackProject({
      prompt,
      rawPrompt,
      currentFiles,
      config,
    }));
  } catch (error) {
    const fallback = buildFallbackProject({
      prompt,
      rawPrompt,
      currentFiles,
      config,
    });

    return res.status(200).json({
      ...fallback,
      assistantMessage: `${fallback.assistantMessage} OpenAI generation failed, so template mode was used instead.`,
      warning: error.message,
    });
  }
}
