import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

async function readJsonSafe(filePath) {
    try {
        return JSON.parse(await fs.readFile(filePath, 'utf8'));
    } catch {
        return null;
    }
}

function resolveWorkspacePath() {
    return process.env.OPENCLAW_WORKSPACE || path.join(os.homedir(), '.openclaw', 'workspace-ocdev');
}

export default async function handler(req, res) {
    if (req.method !== 'GET') {
        res.setHeader('Allow', 'GET');
        return res.status(405).json({ error: 'Method Not Allowed' });
    }

    try {
        // Prefer fresh ticker JSON generated by ticker-site workflow
        let tickerData = null;
        let source = 'static-cache';

        try {
            const primary = await fetch('https://raw.githubusercontent.com/richducat/ticker-site/main/docs/data.json', {
                headers: { 'User-Agent': 'FundManager-EB28/1.0' },
            });
            if (primary.ok) {
                tickerData = await primary.json();
                source = 'ticker-site/data.json';
            }
        } catch {
            // fallback below
        }

        if (!tickerData) {
            const response = await fetch('https://freeopenclawtrader.com', {
                headers: { 'User-Agent': 'FundManager-EB28/1.0' },
            });

            if (!response.ok) {
                throw new Error(`Upstream returned ${response.status}`);
            }

            const html = await response.text();
            const match = html.match(/window\.TICKER_DATA\s*=\s*(\{[\s\S]*?\});/);
            if (!match) {
                return res.status(200).json({
                    ok: true,
                    source: 'freeopenclawtrader.com',
                    data: null,
                    error: 'No TICKER_DATA found in upstream HTML',
                });
            }

            try {
                tickerData = JSON.parse(match[1]);
                source = 'freeopenclawtrader.com';
            } catch (parseError) {
                return res.status(200).json({
                    ok: false,
                    source: 'freeopenclawtrader.com',
                    data: null,
                    error: `Failed to parse TICKER_DATA: ${parseError.message}`,
                });
            }
        }

        // Structure data for the Fund Manager agents
        const botStatuses = [];
        if (tickerData.botActivityText) {
            const parts = tickerData.botActivityText.split('•').map(s => s.trim());
            for (const part of parts) {
                const colonIdx = part.indexOf(':');
                if (colonIdx > 0) {
                    botStatuses.push({
                        name: part.slice(0, colonIdx).trim(),
                        status: part.slice(colonIdx + 1).trim(),
                    });
                }
            }
        }

        // Parse trade logs
        const tradeLogs = [];
        if (tickerData.logsList) {
            const lines = tickerData.logsList.split('\n').filter(Boolean);
            for (const line of lines) {
                tradeLogs.push(line.trim());
            }
        }

        // Parse positions
        const positions = [];
        if (tickerData.positionsList) {
            const lines = tickerData.positionsList.split('\n').filter(Boolean);
            for (const line of lines) {
                const parts = line.split('|').map(s => s.trim());
                if (parts.length >= 4) {
                    positions.push({
                        symbol: parts[0],
                        type: parts[1],
                        cost: parts[2]?.replace('cost ', ''),
                        pnl: parts[3]?.replace('pnl ', ''),
                    });
                }
            }
        }

        const workspace = resolveWorkspacePath();
        const committee = await readJsonSafe(path.join(workspace, 'ops', 'committee', 'outputs', 'committee_decision.json'));
        const orchestrator = await readJsonSafe(path.join(workspace, 'ops', 'reports', 'live_orchestrator_state.json'));

        res.setHeader('Cache-Control', 'no-store');
        res.setHeader('Access-Control-Allow-Origin', '*');
        return res.status(200).json({
            ok: true,
            source,
            updatedAt: tickerData.updatedAt || new Date().toISOString(),
            portfolio: {
                balance: tickerData.balanceUsd || '$0.00',
                exposure: tickerData.exposureUsd || '$0.00',
                totalPnl: tickerData.totalPnlUsd || '$0.00',
                positionsCount: tickerData.positionsCount || 0,
                winRate: tickerData.winRate || '--',
                profitFactor: tickerData.profitFactor || '--',
                drawdown: tickerData.drawdown || '--',
            },
            bots: botStatuses,
            trades: tradeLogs,
            positions,
            botPerf: tickerData.botPerf || '',
            accountStatus: tickerData.accountStatus || 'UNKNOWN',
            latency: tickerData.latency || '--',
            committee: committee ? {
                decision: committee.decision,
                direction: committee.direction,
                confidence: committee.confidence,
                blockers: committee.blockers || [],
            } : null,
            orchestrator: orchestrator ? {
                status: orchestrator?.result?.ran ? 'RUNNING' : 'IDLE',
                lastCycle: orchestrator?.lastCycle || null,
                detail: orchestrator?.result || null,
            } : null,
        });
    } catch (error) {
        res.setHeader('Cache-Control', 'no-store');
        return res.status(500).json({
            ok: false,
            error: `Failed to fetch upstream data: ${error.message}`,
        });
    }
}
